### ISSUE TITLE
Task: Vertical structures

### ISSUE THREAD

**Issue by dhruvbalwada** [dhruvbalwada/sogos#10]
Task: Vertical Structure

## Task Description

We want some metrics to quantify the vertical structure we see in the tracers, in particular the passive tracers. 

- [x] Vertical coherence and vertical spectra of the tracers can be used to estimate how stirring takes place along isopycnals. 
- [x] Looking at ways to quantify layering as done by Scherbina might help with visualization.
- [x] Think about whether the anomalies need to be normalized based on background gradients.

## Epic Parent

[Epic: Do analysis to estimate traditional scales #5](#5)

**Comment by dhruvbalwada** [comment]
It might not be necessary to look at the vertical coherence as the layering already shows what is going on. We can look at this if needed later. 

The vertical spectra could likely be computed but it is unclear how to interpret them at the moment. We can dig into this if there is time later.

**Comment by dhruvbalwada** [comment]
For the vertical spectra calculation we will need to rescale the vertical coordinate. Likely a N/f scaling should work, but let's double check that. 
- [x] Read Smith and Ferrari 2009 
- [x] Apply scaling and estimate the vertical spectra again.

**Comment by dhruvbalwada** [comment]
Tried normalizing the vertical spectra after having normalized for mean variance and standard deviation, and it made little difference to the main result.
