### ISSUE TITLE
Task: Mixed layer analysis

### ISSUE THREAD

**Issue by dhruvbalwada** [dhruvbalwada/sogos#20]
# Task: Mixed layer analysis 

## Task Description

This Task will analyze the properties of the mixed layer, thinking about the stirring. The idea is to go beyond what was done in Dove et al paper.
The things we want to quantify are: 

- [x] Mixed layer depths.
- [x] Read Swart et al. (https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019GL086649) 
- [ ] ~Homogeneity/heterogeneity over the mixed layer. (this will likely be only in T and S)~
- [x] Horizontal gradients in the mixed layer using multiple scales. 
- [x] quantification of how much T vs S contributes to this.
- [x] Coherence estimation for understanding properties. This is (not) similar to Ferrari and Rudnick 2000.
